#!/usr/bin/env python3
"""Pin each Codex arm to its model via an isolated CODEX_HOME.

Why not just pass `-c model=...`?  Because it does not work on the MCP path.
Verified empirically:

    codex exec       -c model="gpt-5.4-mini"   -> model: gpt-5.4-mini   (applied)
    codex mcp-server -c model="gpt-5.4-mini"   -> model: gpt-5.6-sol    (IGNORED)

The mcp-server silently fell back to the user's global config.toml default, which
is a frontier model. That turned the "cheap helper" arm into a second expensive
model without any error -- and it would have quietly invalidated the whole result.

An isolated CODEX_HOME with its own config.toml cannot be ignored. It also keeps
MoCA's Codex sessions out of the user's personal ~/.codex/sessions, so we can
never mis-attribute their day-to-day Codex usage to a run.

CREDENTIAL WARNING: this copies ~/.codex/auth.json into harness/codex_home_*/ so
the isolated homes can authenticate. Those directories are gitignored and MUST
stay that way. Anyone cloning the repo regenerates them by running this script.
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

HARNESS = Path(__file__).resolve().parent
USER_CODEX = Path.home() / ".codex"

HOMES = {
    "codex_home_helper": {"model": "gpt-5.4-mini", "effort": "low"},
    "codex_home_solo":     {"model": "gpt-5.5",      "effort": "medium"},
}

CONFIG = """\
# Generated by setup_codex_homes.py -- pins this arm's model.
# Do not rely on `-c model=` here: mcp-server ignores it (see module docstring).
model = "{model}"
model_reasoning_effort = "{effort}"
approval_policy = "never"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = false   # SWE-bench solutions are public PRs. No lookups.
"""


def main() -> None:
    auth = USER_CODEX / "auth.json"
    if not auth.exists():
        sys.exit(f"no {auth} -- run `codex login` first")

    for name, cfg in HOMES.items():
        home = HARNESS / name
        home.mkdir(exist_ok=True)
        (home / "config.toml").write_text(CONFIG.format(**cfg))
        shutil.copy2(auth, home / "auth.json")     # same account, isolated state
        (home / "auth.json").chmod(0o600)
        print(f"  {name}: model={cfg['model']} effort={cfg['effort']}")

    gitignore = HARNESS.parent / ".gitignore"
    if "codex_home_" not in (gitignore.read_text() if gitignore.exists() else ""):
        sys.exit("REFUSING TO CONTINUE: harness/codex_home_*/ is not gitignored, "
                 "and it now contains a copy of your auth.json.")
    print("\n  (auth.json copied into both homes; they are gitignored, keep it that way)")


if __name__ == "__main__":
    main()
